# Generated by Django 5.1.4 on 2025-01-01 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=350)),
                ('subtitle', models.CharField(default='', max_length=350, null=True)),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('published_date', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('Business Analytics', 'Business Analytics'), ('deep learning', 'deep learning'), ('Python', 'python'), ('Data Science', 'data science'), ('Maths', 'maths'), ('Data ethics', 'Data ethics'), ('NLP', 'NLP'), ('R Studio', 'R Studio'), ('SQL', 'SQL'), ('statistics', 'statistics'), ('visualization', 'visualization')], max_length=100, null=True)),
                ('distribution_expense', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
