# Generated by Django 5.1.4 on 2025-01-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_alter_book_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='uid',
            field=models.CharField(max_length=100),
        ),
    ]
