# Generated by Django 5.1.4 on 2025-01-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_alter_book_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Business Analytics', 'Business Analytics'), ('deep learning', 'deep learning'), ('Python', 'python'), ('Data Science', 'data science'), ('Maths', 'maths'), ('Data ethics', 'Data ethics'), ('NLP', 'NLP'), ('R Studio', 'R Studio'), ('SQL', 'SQL'), ('statistics', 'statistics'), ('visualization', 'visualization')], max_length=100, null=True),
        ),
    ]
